### ISSUE TITLE
Brandon Sort your shit pls

### ISSUE THREAD

**Issue by kierandowns** [gojeffcho/turingterminal#7]
Examine why Brandon's login screen doesn't work like Jeff

Kieran test with your stuff

**Comment by kierandowns** [comment]
<img width="931" alt="screen shot 2017-10-23 at 11 58 34 am" src="https://user-images.githubusercontent.com/15369035/31904882-a3b85852-b7e9-11e7-8a20-4b00cde8986c.png">

Tested on my Mac, I believe it's a UNIX/Mac issue. Further investigation needed. Just be careful where we use "$" then?

**Comment by gojeffcho** [comment]
Not sure what this was about, but pretty sure Brandon fixed the font issue during that meeting.

**Comment by kierandowns** [comment]
What was the fix? I believe I still have the issue.

**Comment by kierandowns** [comment]
Ah I understand. I thought it was $ instead of squares for the ASCII. No issue then!
