### ISSUE TITLE
Add Logout functionality

### ISSUE THREAD

**Issue by gojeffcho** [gojeffcho/turingterminal#9]
When time is up, initiate a logout procedure.

**Comment by kierandowns** [comment]
Would we want to initiate? Or force the user to only be able to initiate logout? (Ex. You type mail.app and it would give you an alert sound, and output **WORKERS MUST ADHERE TO WORKING DAY GUIDLINES**)

**Comment by gojeffcho** [comment]
@kierandowns Kind of both; how I have it right now is that after 4PM, it starts warning you that you must log out before 5PM, and if it reaches 5PM or beyond, the system will force you to log off.

**Comment by gojeffcho** [comment]
RESOLUTION: when the user has no emails or chats remaining for the day, when they return to mainscreen, they are automatically notified and taken to the logout dialog.  Logging out currently invokes $new_day() and goes back to the login screen - we have room to add in logout aesthetics, movie, music, etc. here and handle for days dynamically.
